//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.17 at 07:44:40 PM EET 
//


package com.example.api.second_api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="joined" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="contractExpires" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="contractOption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="currentClubID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="previousClubID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "joined",
    "contractExpires",
    "contractOption"
})
@XmlRootElement(name = "contract")
public class Contract {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar joined;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractExpires;
    @XmlElement(required = true)
    protected String contractOption;
    @XmlAttribute(name = "currentClubID")
    protected String currentClubID;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "previousClubID")
    protected String previousClubID;

    /**
     * Gets the value of the joined property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getJoined() {
        return joined;
    }

    /**
     * Sets the value of the joined property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setJoined(XMLGregorianCalendar value) {
        this.joined = value;
    }

    /**
     * Gets the value of the contractExpires property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractExpires() {
        return contractExpires;
    }

    /**
     * Sets the value of the contractExpires property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractExpires(XMLGregorianCalendar value) {
        this.contractExpires = value;
    }

    /**
     * Gets the value of the contractOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractOption() {
        return contractOption;
    }

    /**
     * Sets the value of the contractOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractOption(String value) {
        this.contractOption = value;
    }

    /**
     * Gets the value of the currentClubID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentClubID() {
        return currentClubID;
    }

    /**
     * Sets the value of the currentClubID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentClubID(String value) {
        this.currentClubID = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the previousClubID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousClubID() {
        return previousClubID;
    }

    /**
     * Sets the value of the previousClubID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousClubID(String value) {
        this.previousClubID = value;
    }

}
