//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.17 at 08:28:11 PM EET 
//


package com.example.api.second_api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="squadSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="averageAge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="stadium" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manager" type="{http://example.com/api/second-api}managerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "squadSize",
    "averageAge",
    "stadium",
    "manager"
})
@XmlRootElement(name = "footballClub")
public class FootballClub {

    @XmlElement(required = true)
    protected String name;
    protected int squadSize;
    protected double averageAge;
    @XmlElement(required = true)
    protected String stadium;
    @XmlElement(required = true)
    protected ManagerType manager;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the squadSize property.
     * 
     */
    public int getSquadSize() {
        return squadSize;
    }

    /**
     * Sets the value of the squadSize property.
     * 
     */
    public void setSquadSize(int value) {
        this.squadSize = value;
    }

    /**
     * Gets the value of the averageAge property.
     * 
     */
    public double getAverageAge() {
        return averageAge;
    }

    /**
     * Sets the value of the averageAge property.
     * 
     */
    public void setAverageAge(double value) {
        this.averageAge = value;
    }

    /**
     * Gets the value of the stadium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStadium() {
        return stadium;
    }

    /**
     * Sets the value of the stadium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStadium(String value) {
        this.stadium = value;
    }

    /**
     * Gets the value of the manager property.
     * 
     * @return
     *     possible object is
     *     {@link ManagerType }
     *     
     */
    public ManagerType getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagerType }
     *     
     */
    public void setManager(ManagerType value) {
        this.manager = value;
    }

}
