//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 01:42:23 PM EET 
//


package com.example.api.second_api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.api.second_api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.api.second_api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlayersByNRequest }
     * 
     */
    public PlayersByNRequest createPlayersByNRequest() {
        return new PlayersByNRequest();
    }

    /**
     * Create an instance of {@link ServerResponse }
     * 
     */
    public ServerResponse createServerResponse() {
        return new ServerResponse();
    }

    /**
     * Create an instance of {@link PlayersRequest }
     * 
     */
    public PlayersRequest createPlayersRequest() {
        return new PlayersRequest();
    }

    /**
     * Create an instance of {@link UpdateContract }
     * 
     */
    public UpdateContract createUpdateContract() {
        return new UpdateContract();
    }

    /**
     * Create an instance of {@link ManagersRequest }
     * 
     */
    public ManagersRequest createManagersRequest() {
        return new ManagersRequest();
    }

    /**
     * Create an instance of {@link ExistDBRemovePlayerRequest }
     * 
     */
    public ExistDBRemovePlayerRequest createExistDBRemovePlayerRequest() {
        return new ExistDBRemovePlayerRequest();
    }

    /**
     * Create an instance of {@link PlayerIDType }
     * 
     */
    public PlayerIDType createPlayerIDType() {
        return new PlayerIDType();
    }

    /**
     * Create an instance of {@link ContractOptionRequest }
     * 
     */
    public ContractOptionRequest createContractOptionRequest() {
        return new ContractOptionRequest();
    }

    /**
     * Create an instance of {@link ExistDBPlayersByCFRequest }
     * 
     */
    public ExistDBPlayersByCFRequest createExistDBPlayersByCFRequest() {
        return new ExistDBPlayersByCFRequest();
    }

    /**
     * Create an instance of {@link ExistDBPlayersByNRequest }
     * 
     */
    public ExistDBPlayersByNRequest createExistDBPlayersByNRequest() {
        return new ExistDBPlayersByNRequest();
    }

    /**
     * Create an instance of {@link RemovePlayerRequest }
     * 
     */
    public RemovePlayerRequest createRemovePlayerRequest() {
        return new RemovePlayerRequest();
    }

    /**
     * Create an instance of {@link ContractOptionResponse }
     * 
     */
    public ContractOptionResponse createContractOptionResponse() {
        return new ContractOptionResponse();
    }

    /**
     * Create an instance of {@link PlayersByCFRequest }
     * 
     */
    public PlayersByCFRequest createPlayersByCFRequest() {
        return new PlayersByCFRequest();
    }

    /**
     * Create an instance of {@link Managers }
     * 
     */
    public Managers createManagers() {
        return new Managers();
    }

    /**
     * Create an instance of {@link ManagerType }
     * 
     */
    public ManagerType createManagerType() {
        return new ManagerType();
    }

    /**
     * Create an instance of {@link UpdateManager }
     * 
     */
    public UpdateManager createUpdateManager() {
        return new UpdateManager();
    }

    /**
     * Create an instance of {@link ExistDBPlayersRequest }
     * 
     */
    public ExistDBPlayersRequest createExistDBPlayersRequest() {
        return new ExistDBPlayersRequest();
    }

    /**
     * Create an instance of {@link ExistDBManagersRequest }
     * 
     */
    public ExistDBManagersRequest createExistDBManagersRequest() {
        return new ExistDBManagersRequest();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link ExistDBContractOptionRequest }
     * 
     */
    public ExistDBContractOptionRequest createExistDBContractOptionRequest() {
        return new ExistDBContractOptionRequest();
    }

    /**
     * Create an instance of {@link Players }
     * 
     */
    public Players createPlayers() {
        return new Players();
    }

    /**
     * Create an instance of {@link PlayerType }
     * 
     */
    public PlayerType createPlayerType() {
        return new PlayerType();
    }

}
