//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 01:42:23 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/api/second-api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.api.second_api;
